name: gtk-theme-nordic
version: "0"
base: core18
architectures:
  - all
summary: GTK Theme Nordic
description: |
  This snap provides the GTK themes for GTK3 theme Nordic in a form
  that can be used by snapped applications. It can be installed alongside
  the gtk-common-themes snap.
grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/nordic
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/nordic

parts:
  theme:
    plugin: dump
    # downloaded from https://www.gnome-look.org/p/1267246/
    source: ./Nordic.tar.xz
    organize:
      gtk-*: share/themes/nordic/
    stage:
      - share/themes/*/gtk-*
